# Reference: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method
# Reference: https://github.com/mmistakes/mm-github-pages-starter

title: Utku Özdemir
email: utku@utkuozdemir.org
description: >- # this means to ignore newlines until "baseurl:"
  Utku Özdemir.
  Software Engineer/Team Lead.
  Cloud, Infrastructure, Kubernetes, Backend Development.
  Living in Berlin.
twitter_username: utkuozdemir
github_username: utkuozdemir
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.19.1
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Utku Özdemir"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software Engineer/Team Lead. Cloud, Infrastructure, Kubernetes, Backend Development. Living in Berlin."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://utkuozdemir.org"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/utkuozdemir"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/utkuozdemir"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/utkuozdemir/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/utkuo89"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/utkuozdemir"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/utkuozdemir"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/utkuozdemir/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/utkuo89"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
