# Reference: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#remote-theme-method
# Reference: https://github.com/mmistakes/mm-github-pages-starter
# Reference: https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# Reference: https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

title: Utku Özdemir
locale: en-US
url: https://utkuozdemir.org
repository: utkuozdemir/utkuozdemir.github.io
description: >-
  Utku Özdemir.
  Software Engineer/Team Lead.
  Cloud, Infrastructure, Kubernetes, Backend Development.
  Living in Berlin.
minimal_mistakes_skin: default
search: true
encoding: utf-8
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.23.0
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Berlin

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name: Utku Özdemir
  location: Berlin, Germany
  email: utku@utkuozdemir.org
  avatar: /assets/images/bio-photo.jpg
  bio: Software Engineer/Team Lead. Cloud, Infrastructure, Kubernetes, Backend Development. Living in Berlin.
  links:
    - label: CV
      icon: fas fa-fw fa-file-pdf
      url: /cv/utku-ozdemir-cv.pdf
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/utkuozdemir
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/utkuozdemir
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/utkuozdemir/
    - label: Stack Overflow
      icon: fab fa-fw fa-stack-overflow
      url: https://stackoverflow.com/users/1005102

footer:
  links:
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/utkuozdemir
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/utkuozdemir
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/utkuozdemir/
    - label: Stack Overflow
      icon: fab fa-fw fa-stack-overflow
      url: https://stackoverflow.com/users/1005102

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
#  ignore:
#    envs: development

analytics:
  provider: google-gtag
  google:
    tracking_id: UA-63153932-2
    anonymize_ip: false
